import type { EntryLineSide } from "./types";

const ACCOUNT_SYNONYMS: Record<string, string> = {
  cash: "Cash",
  "cash account": "Cash",
  bank: "Bank",
  "bank account": "Bank",
  capital: "Capital",
  "owner capital": "Capital",
  "proprietor capital": "Capital",
  drawings: "Drawings",
  "drawings account": "Drawings",
  drawing: "Drawings",
  "drawing account": "Drawings",
  "owner drawings": "Drawings",
  "proprietor drawings": "Drawings",
  purchases: "Purchases",
  "purchases account": "Purchases",
  purchase: "Purchases",
  "purchase account": "Purchases",
  sales: "Sales",
  "sales account": "Sales",
  sale: "Sales",
  "sale account": "Sales",
  "sales revenue": "Sales",
  advertisement: "Advertisement Expense",
  "advertisement account": "Advertisement Expense",
  "advertisement expense": "Advertisement Expense",
  "advertisement expense account": "Advertisement Expense",
  advertising: "Advertisement Expense",
  "advertising account": "Advertisement Expense",
  "advertising expense": "Advertisement Expense",
  "advertising expense account": "Advertisement Expense",
  promotion: "Advertisement Expense",
  "promotion account": "Advertisement Expense",
  "promotion expense": "Advertisement Expense",
  "promotion expense account": "Advertisement Expense",
  promotional: "Advertisement Expense",
  "promotional expense": "Advertisement Expense",
  "promotional expense account": "Advertisement Expense",
  charity: "Charity Expense",
  "charity account": "Charity Expense",
  "charity expense": "Charity Expense",
  "charity expense account": "Charity Expense",
  donation: "Charity Expense",
  "donation account": "Charity Expense",
  "donation expense": "Charity Expense",
  "donation expense account": "Charity Expense",
  donations: "Charity Expense",
  "donations account": "Charity Expense",
  "loss by fire": "Loss by Fire",
  "loss by fire account": "Loss by Fire",
  "goods lost by fire": "Loss by Fire",
  "fire loss": "Loss by Fire",
  "fire loss account": "Loss by Fire",
  "goods destroyed by fire": "Loss by Fire",
  "goods damaged by fire": "Loss by Fire",
  "loss by theft": "Loss by Theft",
  "loss by theft account": "Loss by Theft",
  "goods lost by theft": "Loss by Theft",
  "theft loss": "Loss by Theft",
  "theft loss account": "Loss by Theft",
  "goods stolen": "Loss by Theft",
  "stolen goods": "Loss by Theft",
  "goods lost": "Goods Lost",
  "goods lost account": "Goods Lost",
  "loss of goods": "Goods Lost",
  "goods damaged": "Goods Lost",
  "damaged goods": "Goods Lost",
  "accidental loss": "Goods Lost",
  "accidental loss account": "Goods Lost",
  "bad debt": "Bad Debts",
  "bad debts": "Bad Debts",
  "bad debt account": "Bad Debts",
  "bad debts account": "Bad Debts",
  "bad debt expense": "Bad Debts",
  "bad debts expense": "Bad Debts",
  "bad debt recovered": "Bad Debts Recovered",
  "bad debts recovered": "Bad Debts Recovered",
  "bad debt recovered account": "Bad Debts Recovered",
  "bad debts recovered account": "Bad Debts Recovered",
  "bad debts recovery": "Bad Debts Recovered",
  "bad debts recovery income": "Bad Debts Recovered",
  "discount allowed": "Discount Allowed",
  "discount allowed account": "Discount Allowed",
  "discount given": "Discount Allowed",
  "discount allowed expense": "Discount Allowed",
  "discount received": "Discount Received",
  "discount received account": "Discount Received",
  "discount earned": "Discount Received",
  "discount received income": "Discount Received",
  depreciation: "Depreciation",
  "depreciation account": "Depreciation",
  "depreciation expense": "Depreciation",
  furniture: "Furniture",
  machinery: "Machinery",
  computer: "Computer",
  computers: "Computer",
  equipment: "Equipment",
  vehicle: "Vehicle",
  vehicles: "Vehicle",
  rent: "Rent Expense",
  "rent account": "Rent Expense",
  "rent expense": "Rent Expense",
  "rent expense account": "Rent Expense",
  "shop rent": "Rent Expense",
  "outstanding rent": "Outstanding Rent",
  "rent outstanding": "Outstanding Rent",
  "rent payable": "Outstanding Rent",
  "prepaid rent": "Prepaid Rent",
  "rent prepaid": "Prepaid Rent",
  "advance rent": "Prepaid Rent",
  "rent paid in advance": "Prepaid Rent",
  "accrued rent": "Accrued Rent",
  "rent accrued": "Accrued Rent",
  "rent receivable": "Accrued Rent",
  "rent due": "Accrued Rent",
  "rent income": "Rent Income",
  "rent received": "Rent Income",
  "rent earned": "Rent Income",
  "rent received in advance": "Rent Received in Advance",
  "advance rent received": "Rent Received in Advance",
  "unearned rent": "Rent Received in Advance",
  "rent received beforehand": "Rent Received in Advance",
  salary: "Salary Expense",
  "salary account": "Salary Expense",
  salaries: "Salary Expense",
  "salary expense": "Salary Expense",
  "salary expense account": "Salary Expense",
  "staff salary": "Salary Expense",
  "employee salary": "Salary Expense",
  "outstanding salary": "Outstanding Salary",
  "salary outstanding": "Outstanding Salary",
  "salary payable": "Outstanding Salary",
  "prepaid salary": "Prepaid Salary",
  "salary prepaid": "Prepaid Salary",
  "advance salary": "Prepaid Salary",
  "salary paid in advance": "Prepaid Salary",
  wages: "Wages Expense",
  wage: "Wages Expense",
  "wages account": "Wages Expense",
  "wages expense": "Wages Expense",
  "wages expense account": "Wages Expense",
  "wage account": "Wages Expense",
  "wage expense": "Wages Expense",
  "outstanding wages": "Outstanding Wages",
  "wages outstanding": "Outstanding Wages",
  "wages payable": "Outstanding Wages",
  "prepaid wages": "Prepaid Wages",
  "wages prepaid": "Prepaid Wages",
  "advance wages": "Prepaid Wages",
  "wages paid in advance": "Prepaid Wages",
  commission: "Commission Income",
  "commission income": "Commission Income",
  "commission received": "Commission Income",
  "commission earned": "Commission Income",
  "accrued commission": "Accrued Commission",
  "commission accrued": "Accrued Commission",
  "commission receivable": "Accrued Commission",
  "commission due": "Accrued Commission",
  "commission received in advance": "Commission Received in Advance",
  "advance commission received": "Commission Received in Advance",
  "unearned commission": "Commission Received in Advance",
  "commission received beforehand": "Commission Received in Advance",
  "interest expense": "Interest Expense",
  "interest paid": "Interest Expense",
  "interest on loan": "Interest Expense",
  "loan interest": "Interest Expense",
  "interest income": "Interest Income",
  "interest received": "Interest Income",
  "interest earned": "Interest Income",
  "accrued interest": "Accrued Interest",
  "interest accrued": "Accrued Interest",
  "interest receivable": "Accrued Interest",
  "interest due": "Accrued Interest",
  "interest received in advance": "Interest Received in Advance",
  "advance interest received": "Interest Received in Advance",
  "unearned interest": "Interest Received in Advance",
  "interest received beforehand": "Interest Received in Advance",
  electricity: "Electricity Expense",
  "electricity expense": "Electricity Expense",
  "electricity bill": "Electricity Expense",
  "electricity account": "Electricity Expense",
  "electricity expense account": "Electricity Expense",
  "outstanding electricity": "Outstanding Electricity",
  "electricity outstanding": "Outstanding Electricity",
  "electricity payable": "Outstanding Electricity",
  "outstanding electricity bill": "Outstanding Electricity",
  "prepaid electricity": "Prepaid Electricity",
  "electricity prepaid": "Prepaid Electricity",
  "advance electricity": "Prepaid Electricity",
  "electricity paid in advance": "Prepaid Electricity",
  insurance: "Insurance Expense",
  "insurance account": "Insurance Expense",
  "insurance premium": "Insurance Expense",
  "insurance expense": "Insurance Expense",
  "insurance expense account": "Insurance Expense",
  "outstanding insurance": "Outstanding Insurance",
  "insurance outstanding": "Outstanding Insurance",
  "insurance payable": "Outstanding Insurance",
  "prepaid insurance": "Prepaid Insurance",
  "insurance prepaid": "Prepaid Insurance",
  "advance insurance": "Prepaid Insurance",
  "insurance paid in advance": "Prepaid Insurance",
  debtor: "Debtor",
  debtors: "Debtor",
  "debtor account": "Debtor",
  "sundry debtor": "Debtor",
  "sundry debtors": "Debtor",
  customer: "Debtor",
  creditor: "Creditor",
  creditors: "Creditor",
  "creditor account": "Creditor",
  "sundry creditor": "Creditor",
  "sundry creditors": "Creditor",
  supplier: "Creditor",
  loan: "Loan",
  "bank loan": "Loan",
  borrowings: "Loan",
  "borrowed loan": "Loan",
};

const SPELLING_CORRECTIONS: Record<string, string> = {
  capitol: "capital",
  salery: "salary",
  purchse: "purchases",
  commision: "commission",
  machinary: "machinery",
  furnitur: "furniture",
  crediter: "creditor",
  debter: "debtor",
};

export function cleanAccountName(value: string): string {
  const cleaned = value
    .toLowerCase()
    .replace(/\ba\s*\/?\s*c\b|\bac\b|\baccount\b/g, " account ")
    .replace(/\bdr\b|\bcr\b|\bdebit\b|\bcredit\b|\bto\b/g, " ")
    .replace(/[.:,()]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  return applySpellingCorrections(cleaned)
    .replace(/\baccount\b/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function normalizeAccountName(value: string, side?: EntryLineSide): string {
  const cleaned = cleanAccountName(value);

  if (cleaned === "interest") {
    return side === "credit" ? "Interest Income" : "Interest Expense";
  }

  if (cleaned === "goods") {
    return side === "credit" ? "Sales" : "Purchases";
  }

  return ACCOUNT_SYNONYMS[cleaned] ?? titleCase(cleaned);
}

function applySpellingCorrections(value: string): string {
  return value
    .split(" ")
    .map((word) => SPELLING_CORRECTIONS[word] ?? word)
    .join(" ");
}

function titleCase(value: string): string {
  return value
    .split(" ")
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
